version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - "echo Entered the install phase..."
      - "echo Installing FFmpeg..."
      - "cd /usr/local/bin"
      - "uname -a"
      - "wget -O /tmp/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-5.0.1-amd64-static.tar.xz"
      - "mkdir -p /opt/ffmpeg"
      - "tar xvf /tmp/ffmpeg.tar.xz -C /opt/ffmpeg"
      - "echo FFmpeg version:"
      - "/opt/ffmpeg ls"
      - "/opt/ffmpeg/ffmpeg -version"
      - "cp -a /usr/local/bin/ffmpeg/ffmpeg-5.0.1-amd64-static/ . /usr/local/bin/ffmpeg/"
      - "ln -s /usr/local/bin/ffmpeg/ffmpeg /usr/bin/ffmpeg"
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
