version: 0.2

phases:
  install:
    commands:
      - echo "Entered the install phase..."
      - "wget -O /tmp/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"
      - "if [ ! -d /opt/ffmpeg ] ; then mkdir -p /opt/ffmpeg; fi"
      - "tar xvf /tmp/ffmpeg.tar.xz -C /opt/ffmpeg"
      - "if [[ ! -f /usr/bin/ffmpeg ]] ; then ln -sf /opt/ffmpeg/ffmpeg-4.2.2-amd64-static/ffmpeg /usr/bin/ffmpeg; fi"
      - "if [[ ! -f /usr/bin/ffprobe ]] ; then ln -sf /opt/ffmpeg/ffmpeg-4.2.2-amd64-static/ffprobe /usr/bin/ffprobe; fi"
      - "if [ `pecl list | grep imagick` ] ; then pecl install -f imagick; fi"
      - echo "Successfully installed ffmpeg"
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
